# Generated by Django 4.1.1 on 2022-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('training_plan', models.CharField(default=None, max_length=256)),
                ('run_name', models.CharField(default=None, max_length=64)),
                ('running_time', models.TimeField()),
                ('paste', models.TimeField()),
                ('shoes', models.CharField(max_length=64)),
                ('comment', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_model', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('description', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
