# Generated by Django 4.1.1 on 2022-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_runparameters_shoes_trainingplan_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='runparameters',
            name='distance',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='runparameters',
            name='pulse_avg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='runparameters',
            name='pulse_max',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='runparameters',
            name='rhythm_avg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='runparameters',
            name='rise',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='runparameters',
            name='step_avg',
            field=models.FloatField(default=None),
        ),
    ]
