# Generated by Django 4.1.1 on 2022-09-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_rename_runparameters_runparameter_rename_shoes_shoe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runparameter',
            name='paste',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='pulse_avg',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='pulse_max',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='rhythm_avg',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='rise',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='running_time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='runparameter',
            name='step_avg',
            field=models.CharField(max_length=32),
        ),
    ]
